### ISSUE TITLE
Use stricter type checking options 

### ISSUE THREAD

**Issue by thec00n** [SmartContractSecurity/SWC-registry-javascript#5]
See https://github.com/ConsenSys/maru/blob/master/tsconfig.json

**Comment by ersul4ik** [comment]
Currently, swc-registry@1.0.1 have a stricter type of tsconfig.json

**Comment by ersul4ik** [comment]
No. I think it can be closed

**Comment by blitz-1306** [comment]
@thec00n strictness requirements should be fullfilled in https://github.com/SmartContractSecurity/SWC-registry-javascript/pull/21. If so, please consider to resolve issue.
